name: Deploy GO Server to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup variables and Generate deployment package
        run: |
          echo "VERSION_LABEL=${{ github.sha }}-$(date +\%s)" >> $GITHUB_ENV

          cd api
          zip -r ../deploy.zip . -x '*.git*'
          cd ..
    
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: golang
            environment_name: main
            version_label: ${{ env.VERSION_LABEL }}
            region: ap-southeast-1
            deployment_package: deploy.zip
